# Generated by Django 4.1 on 2022-08-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CategoryMain',
            new_name='Category_Main',
        ),
    ]
