# Generated by Django 4.1 on 2022-08-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_categorymain_product_category_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_desp',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
