# Generated by Django 3.2.9 on 2022-10-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_deals_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='already_saled',
            field=models.IntegerField(default=23),
        ),
    ]
