# Generated by Django 3.2.9 on 2022-10-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_already_saled'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image_1',
            field=models.ImageField(blank=True, upload_to='Product/product_img/product_diffrent_img'),
        ),
        migrations.AddField(
            model_name='product',
            name='Image_2',
            field=models.ImageField(blank=True, upload_to='Product/product_img/product_diffrent_img'),
        ),
        migrations.AddField(
            model_name='product',
            name='Image_3',
            field=models.ImageField(blank=True, upload_to='Product/product_img/product_diffrent_img'),
        ),
        migrations.AddField(
            model_name='product',
            name='Image_4',
            field=models.ImageField(blank=True, upload_to='Product/product_img/product_diffrent_img'),
        ),
        migrations.AddField(
            model_name='product',
            name='Image_5',
            field=models.ImageField(blank=True, upload_to='Product/product_img/product_diffrent_img'),
        ),
    ]
