# Generated by Django 4.1 on 2022-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_address_alter_account_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email2',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
