# Generated by Django 3.2.9 on 2022-08-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220828_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner_picture',
            field=models.ImageField(blank=True, upload_to='profile_banner_pics'),
        ),
    ]
