# Generated by Django 3.2.9 on 2022-08-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_banner_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='banner_picture',
        ),
    ]
