# Generated by Django 4.1 on 2022-08-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymain',
            name='cat_img',
        ),
    ]
