# Generated by Django 4.1 on 2022-09-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'New'), ('Accepted', 'Accepted'), ('Ready to ship', 'Ready to ship'), ('On shipping', 'On shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('return', 'return'), ('Refunded', 'Refunded')], default='Accepted', max_length=50),
        ),
    ]
